name: tugas_akhir_pm
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^0.8.7+4
  intl: ^0.18.0
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
